name: Integration Tests

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Hello World
        run: |
          echo "Hello World!"
