name: Integration Test Suite

on: [push]
jobs:
  
  integration-tests:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Run test suite
        uses: cypress-io/github-action@v1
        with:
          start: npm test