name: End-to-end tests

on: [push]
jobs:
  
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Start python server
        run: |
          python -m http.server --directory build/ 1111
      
      - name: Run test suite
        uses: cypress-io/github-action@v1